version: '3.8'
services:
  requester:
    image: ghcr.io/amqp-reply/dummy-project-test-amqp-reply/requester-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: requester
    ports:
      - "8000:8000"
    command: ["symfony", "server:start", "--no-tls", "--port=8000", "--allow-http", "--listen-ip=0.0.0.0"]

#  responder:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        APP_DIR: responder
#    ports:
#      - "8001:8000"
#    command: ["php", "bin/console", "messenger:consume", "async", "--time-limit=3600"]
