services:
  requester:
    image: ghcr.io/amqp-reply/test-requester-amqp-reply:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: ./requester

  responder:
    image: ghcr.io/amqp-reply/test-responder-amqp-reply:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: ./responder
