services:
  requester:
    image: ghcr.io/amqp-reply/test-requester-amqp-reply:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: ./requester
    ports:
      - "8000:8000"
    entrypoint: ["./entrypoint.sh"]
    command: ["symfony", "server:start", "--no-tls", "--port=8000", "--allow-http", "--listen-ip=0.0.0.0"]

  responder:
    image: ghcr.io/amqp-reply/test-responder-amqp-reply:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_DIR: ./responder
    ports:
      - "8001:8000"
    entrypoint: ["./entrypoint.sh"]
    command: ["php", "bin/console", "messenger:consume", "my_transport_sync", "--time-limit=3600"]
